packages:
  - name: lib
    type: yarn
    srcs:
      - "src/**"
      - "styles/**"
      - package.json
      - mocha.opts
    deps:
      - components/gitpod-protocol:lib
      - components/supervisor-api/typescript-grpc:lib
    config:
      packaging: library
      yarnLock: ${coreYarnLockBase}/../../yarn.lock
      tsconfig: tsconfig.json
