packages:
  - name: proto
    type: generic
    srcs:
      - "*.proto"
    config:
      commands:
        - ["git", "clone", "https://github.com/grpc-ecosystem/grpc-gateway"]
        - ["mv", "grpc-gateway/third_party", "third_party"]
        - ["rm", "-r", "grpc-gateway"]